using UnityEngine;
public class CategoryPackData : ScriptableObject
{
    // Fields
    public System.Collections.Generic.List<CategoryColor> colorList;
    public static System.Collections.Generic.List<CategoryPackInfo> packList;
    
    // Methods
    public CategoryPackData()
    {
    
    }
    private static CategoryPackData()
    {
        var val_57;
        System.Collections.Generic.List<CategoryPackInfo> val_1 = new System.Collections.Generic.List<CategoryPackInfo>();
        val_57 = null;
        val_57 = null;
        .cost = System.Decimal.Zero;
        .packId = 0;
        .title = "ANIMALS";
        .suffix = "I";
        mem[1152921516120138996] = System.Decimal.Powers10.__il2cppRuntimeField_10;
        .color = 1;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_3 = new System.Decimal(value:  188);
        .packId = 1;
        .title = "ANIMALS";
        .suffix = "II";
        .cost = val_3.flags;
        mem[1152921516120143092] = val_3.lo;
        .color = 1;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_5 = new System.Decimal(value:  144);
        mem[1152921516120147188] = val_5.lo;
        .title = "PLANTS";
        .suffix = "I";
        .cost = val_5.flags;
        .packId = 2;
        .color = 3;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_7 = new System.Decimal(value:  244);
        .packId = 3;
        .title = "COMPUTERS";
        .suffix = "I";
        .cost = val_7.flags;
        mem[1152921516120151284] = val_7.lo;
        .color = 6;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_9 = new System.Decimal(value:  100);
        .title = "SPORTS";
        .suffix = "I";
        .cost = val_9.flags;
        mem[1152921516120155380] = val_9.lo;
        .packId = 4;
        .color = 8;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_11 = new System.Decimal(value:  200);
        .title = "ADJECTIVES";
        .suffix = "I";
        .cost = val_11.flags;
        mem[1152921516120159476] = val_11.lo;
        .color = 2;
        .packId = 5;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_13 = new System.Decimal(value:  44);
        .packId = 6;
        .title = "ADJECTIVES";
        .suffix = "II";
        .cost = val_13.flags;
        mem[1152921516120163572] = val_13.lo;
        .color = 2;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_15 = new System.Decimal(value:  244);
        .title = "ADJECTIVES";
        .suffix = "III";
        .cost = val_15.flags;
        mem[1152921516120167668] = val_15.lo;
        .color = 2;
        .packId = 7;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_17 = new System.Decimal(value:  188);
        .packId = 8;
        .title = "ADJECTIVES";
        .suffix = "IV";
        .cost = val_17.flags;
        mem[1152921516120171764] = val_17.lo;
        .color = 2;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_19 = new System.Decimal(value:  132);
        .title = "ADJECTIVES";
        .suffix = "V";
        .cost = val_19.flags;
        mem[1152921516120175860] = val_19.lo;
        .color = 2;
        .packId = 9;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_21 = new System.Decimal(value:  176);
        .title = "ADJECTIVES";
        .suffix = "VI";
        .cost = val_21.flags;
        mem[1152921516120179956] = val_21.lo;
        .color = 2;
        .packId = 10;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_23 = new System.Decimal(value:  220);
        .title = "ADJECTIVES";
        .suffix = "VII";
        .cost = val_23.flags;
        mem[1152921516120184052] = val_23.lo;
        .color = 2;
        .packId = 11;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_25 = new System.Decimal(value:  200);
        mem[1152921516120188148] = val_25.lo;
        .title = "FOOD";
        .suffix = "I";
        .cost = val_25.flags;
        .color = 7;
        .packId = 12;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_27 = new System.Decimal(value:  176);
        .title = "FOOD";
        .suffix = "II";
        .cost = val_27.flags;
        mem[1152921516120192244] = val_27.lo;
        .color = 7;
        .packId = 13;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_29 = new System.Decimal(value:  44);
        .title = "TRANSPORT";
        .suffix = "I";
        .cost = val_29.flags;
        mem[1152921516120196340] = val_29.lo;
        .color = 4;
        .packId = 14;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_31 = new System.Decimal(value:  144);
        .cost = val_31.flags;
        .title = "ADVERBS";
        .suffix = "I";
        mem[1152921516120200436] = val_31.lo;
        .color = 9;
        .packId = 15;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_33 = new System.Decimal(value:  220);
        .title = "ADVERBS";
        .suffix = "II";
        .cost = val_33.flags;
        mem[1152921516120204532] = val_33.lo;
        .color = 9;
        .packId = 16;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_35 = new System.Decimal(value:  132);
        .title = "SHIPS";
        .suffix = "I";
        .cost = val_35.flags;
        mem[1152921516120208628] = val_35.lo;
        .color = 5;
        .packId = 17;
        .timeLimited = false;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_37 = new System.Decimal(value:  132);
        .packId = 18;
        .title = "SPRING";
        .suffix = "I";
        .cost = val_37.flags;
        mem[1152921516120212724] = val_37.lo;
        .color = 10;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_39 = new System.Decimal(value:  132);
        .title = "SUMMER";
        .suffix = "I";
        .cost = val_39.flags;
        mem[1152921516120216820] = val_39.lo;
        .color = 15;
        .packId = 19;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_41 = new System.Decimal(value:  132);
        .title = "FALL";
        .suffix = "I";
        .cost = val_41.flags;
        mem[1152921516120220916] = val_41.lo;
        .color = 11;
        .packId = 20;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_43 = new System.Decimal(value:  132);
        .title = "WINTER";
        .suffix = "I";
        .cost = val_43.flags;
        mem[1152921516120225012] = val_43.lo;
        .color = 16;
        .packId = 21;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_45 = new System.Decimal(value:  132);
        .title = "HALLOWEEN";
        .suffix = "I";
        .cost = val_45.flags;
        mem[1152921516120229108] = val_45.lo;
        .color = 12;
        .packId = 22;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_47 = new System.Decimal(value:  132);
        .title = "CHRISTMAS";
        .suffix = "I";
        .cost = val_47.flags;
        mem[1152921516120233204] = val_47.lo;
        .color = 17;
        .packId = 23;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_49 = new System.Decimal(value:  132);
        .title = "THANKSGIVING";
        .suffix = "I";
        .cost = val_49.flags;
        mem[1152921516120237300] = val_49.lo;
        .color = 19;
        .packId = 24;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_51 = new System.Decimal(value:  132);
        .title = "INDEPENDENCE DAY";
        .suffix = "I";
        .cost = val_51.flags;
        mem[1152921516120241396] = val_51.lo;
        .color = 13;
        .packId = 25;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_53 = new System.Decimal(value:  132);
        .title = "VALENTINE\'S DAY";
        .suffix = "I";
        .cost = val_53.flags;
        mem[1152921516120245492] = val_53.lo;
        .color = 18;
        .packId = 26;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        decimal val_55 = new System.Decimal(value:  132);
        .title = "BACK TO SCHOOL";
        .suffix = "I";
        .cost = val_55.flags;
        mem[1152921516120249588] = val_55.lo;
        .color = 14;
        .packId = 27;
        .timeLimited = true;
        val_1.Add(item:  new CategoryPackInfo());
        CategoryPackData.packList = val_1;
    }

}
