using UnityEngine;
public class GiftRewardData
{
    // Fields
    public static System.Collections.Generic.List<GiftRewardTypeChance> ChapterRewardTypeChances;
    public static System.Collections.Generic.List<GiftRewardTypeChance> DailyBonusRewardTypeChances;
    public static System.Collections.Generic.List<GiftRewardTypeChance> DailyBonusPickAnotherRewardChances;
    public static System.Collections.Generic.List<GiftRewardTier> DailyBonusCoinRewardTiersV2;
    public static System.Collections.Generic.List<GiftRewardTier> ChapterRewardCoinRewardTiers;
    public static System.Collections.Generic.List<GiftRewardAmountChance> DailyBonusFoodAmountChances;
    public static System.Collections.Generic.List<GiftRewardAmountChance> ChapterRewardFoodAmountChances;
    public static System.Collections.Generic.List<GiftRewardTier> DailyChallengeCoinRewardTiers;
    public static System.Collections.Generic.List<GiftRewardTypeChance> DailyChallengeWeeklyRewardChances;
    public static System.Collections.Generic.List<GiftRewardTypeChance> DailyChallengeMonthlyRewardChances;
    public static System.Collections.Generic.List<GiftRewardAmountChance> DailyChallengeRewardFoodAmountChances;
    
    // Methods
    public GiftRewardData()
    {
    
    }
    private static GiftRewardData()
    {
        System.Collections.Generic.List<GiftRewardTypeChance> val_1 = new System.Collections.Generic.List<GiftRewardTypeChance>();
        .RewardType = 2.12199579096527E-312;
        val_1.Add(item:  new GiftRewardTypeChance());
        .RewardType = 1.06099789553204E-313;
        val_1.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098009E-312;
        val_1.Add(item:  new GiftRewardTypeChance());
        .RewardType = 4.24399158207876E-313;
        val_1.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579111349E-313;
        val_1.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579097515E-312;
        val_1.Add(item:  new GiftRewardTypeChance());
        GiftRewardData.ChapterRewardTypeChances = val_1;
        System.Collections.Generic.List<GiftRewardTypeChance> val_8 = new System.Collections.Generic.List<GiftRewardTypeChance>();
        .RewardType = 2.12199579096527E-312;
        val_8.Add(item:  new GiftRewardTypeChance());
        .RewardType = 1.06099789553204E-313;
        val_8.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098009E-312;
        val_8.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579111349E-313;
        val_8.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579097515E-312;
        val_8.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098503E-312;
        val_8.Add(item:  new GiftRewardTypeChance());
        GiftRewardData.DailyBonusRewardTypeChances = val_8;
        System.Collections.Generic.List<GiftRewardTypeChance> val_15 = new System.Collections.Generic.List<GiftRewardTypeChance>();
        .RewardType = 2.12199579096527E-312;
        val_15.Add(item:  new GiftRewardTypeChance());
        .RewardType = 1.06099789549746E-312;
        val_15.Add(item:  new GiftRewardTypeChance());
        .RewardType = 1.06099789553204E-313;
        val_15.Add(item:  new GiftRewardTypeChance());
        GiftRewardData.DailyBonusPickAnotherRewardChances = val_15;
        System.Collections.Generic.List<GiftRewardTier> val_19 = new System.Collections.Generic.List<GiftRewardTier>();
        System.Collections.Generic.List<System.Object> val_20 = new System.Collections.Generic.List<System.Object>();
        val_20.Add(item:  100);
        val_20.Add(item:  110);
        val_20.Add(item:  120);
        .threshold = "0";
        .rewards = val_20;
        val_19.Add(item:  new GiftRewardTier(threshold:  "0", rewards:  val_20));
        System.Collections.Generic.List<System.Object> val_22 = new System.Collections.Generic.List<System.Object>();
        val_22.Add(item:  70);
        val_22.Add(item:  80);
        val_22.Add(item:  90);
        .threshold = "30";
        .rewards = val_22;
        val_19.Add(item:  new GiftRewardTier(threshold:  "30", rewards:  val_22));
        System.Collections.Generic.List<System.Object> val_24 = new System.Collections.Generic.List<System.Object>();
        val_24.Add(item:  40);
        val_24.Add(item:  45);
        val_24.Add(item:  50);
        .threshold = "60";
        .rewards = val_24;
        val_19.Add(item:  new GiftRewardTier(threshold:  "60", rewards:  val_24));
        System.Collections.Generic.List<System.Object> val_26 = new System.Collections.Generic.List<System.Object>();
        val_26.Add(item:  30);
        val_26.Add(item:  35);
        val_26.Add(item:  40);
        .threshold = "120";
        .rewards = val_26;
        val_19.Add(item:  new GiftRewardTier(threshold:  "120", rewards:  val_26));
        System.Collections.Generic.List<System.Object> val_28 = new System.Collections.Generic.List<System.Object>();
        val_28.Add(item:  20);
        val_28.Add(item:  25);
        val_28.Add(item:  30);
        .threshold = "350";
        .rewards = val_28;
        val_19.Add(item:  new GiftRewardTier(threshold:  "350", rewards:  val_28));
        System.Collections.Generic.List<System.Object> val_30 = new System.Collections.Generic.List<System.Object>();
        val_30.Add(item:  15);
        val_30.Add(item:  20);
        val_30.Add(item:  25);
        .threshold = "500";
        .rewards = val_30;
        val_19.Add(item:  new GiftRewardTier(threshold:  "500", rewards:  val_30));
        System.Collections.Generic.List<System.Object> val_32 = new System.Collections.Generic.List<System.Object>();
        val_32.Add(item:  10);
        val_32.Add(item:  15);
        val_32.Add(item:  10);
        .threshold = "1000";
        .rewards = val_32;
        val_19.Add(item:  new GiftRewardTier(threshold:  "1000", rewards:  val_32));
        GiftRewardData.DailyBonusCoinRewardTiersV2 = val_19;
        System.Collections.Generic.List<GiftRewardTier> val_34 = new System.Collections.Generic.List<GiftRewardTier>();
        System.Collections.Generic.List<System.Object> val_35 = new System.Collections.Generic.List<System.Object>();
        val_35.Add(item:  30);
        val_35.Add(item:  35);
        val_35.Add(item:  40);
        .threshold = "0";
        .rewards = val_35;
        val_34.Add(item:  new GiftRewardTier(threshold:  "0", rewards:  val_35));
        System.Collections.Generic.List<System.Object> val_37 = new System.Collections.Generic.List<System.Object>();
        val_37.Add(item:  20);
        val_37.Add(item:  25);
        val_37.Add(item:  30);
        .threshold = "30";
        .rewards = val_37;
        val_34.Add(item:  new GiftRewardTier(threshold:  "30", rewards:  val_37));
        System.Collections.Generic.List<System.Object> val_39 = new System.Collections.Generic.List<System.Object>();
        val_39.Add(item:  15);
        val_39.Add(item:  20);
        val_39.Add(item:  25);
        .threshold = "60";
        .rewards = val_39;
        val_34.Add(item:  new GiftRewardTier(threshold:  "60", rewards:  val_39));
        System.Collections.Generic.List<System.Object> val_41 = new System.Collections.Generic.List<System.Object>();
        val_41.Add(item:  10);
        val_41.Add(item:  15);
        val_41.Add(item:  20);
        .threshold = "120";
        .rewards = val_41;
        val_34.Add(item:  new GiftRewardTier(threshold:  "120", rewards:  val_41));
        System.Collections.Generic.List<System.Object> val_43 = new System.Collections.Generic.List<System.Object>();
        val_43.Add(item:  5);
        val_43.Add(item:  10);
        val_43.Add(item:  15);
        .threshold = "350";
        .rewards = val_43;
        val_34.Add(item:  new GiftRewardTier(threshold:  "350", rewards:  val_43));
        System.Collections.Generic.List<System.Object> val_45 = new System.Collections.Generic.List<System.Object>();
        val_45.Add(item:  3);
        val_45.Add(item:  5);
        val_45.Add(item:  7);
        .threshold = "500";
        .rewards = val_45;
        val_34.Add(item:  new GiftRewardTier(threshold:  "500", rewards:  val_45));
        GiftRewardData.ChapterRewardCoinRewardTiers = val_34;
        System.Collections.Generic.List<GiftRewardAmountChance> val_47 = new System.Collections.Generic.List<GiftRewardAmountChance>();
        .Amount = 1;
        .Chance = 60f;
        val_47.Add(item:  new GiftRewardAmountChance());
        .Amount = 2;
        .Chance = 40f;
        val_47.Add(item:  new GiftRewardAmountChance());
        GiftRewardData.DailyBonusFoodAmountChances = val_47;
        System.Collections.Generic.List<GiftRewardAmountChance> val_50 = new System.Collections.Generic.List<GiftRewardAmountChance>();
        .Amount = 1;
        .Chance = 60f;
        val_50.Add(item:  new GiftRewardAmountChance());
        .Amount = 2;
        .Chance = 40f;
        val_50.Add(item:  new GiftRewardAmountChance());
        GiftRewardData.ChapterRewardFoodAmountChances = val_50;
        System.Collections.Generic.List<GiftRewardTier> val_53 = new System.Collections.Generic.List<GiftRewardTier>();
        System.Collections.Generic.List<System.Object> val_54 = new System.Collections.Generic.List<System.Object>();
        val_54.Add(item:  100);
        val_54.Add(item:  110);
        val_54.Add(item:  120);
        .threshold = "0";
        .rewards = val_54;
        val_53.Add(item:  new GiftRewardTier(threshold:  "0", rewards:  val_54));
        System.Collections.Generic.List<System.Object> val_56 = new System.Collections.Generic.List<System.Object>();
        val_56.Add(item:  70);
        val_56.Add(item:  80);
        val_56.Add(item:  90);
        .threshold = "30";
        .rewards = val_56;
        val_53.Add(item:  new GiftRewardTier(threshold:  "30", rewards:  val_56));
        System.Collections.Generic.List<System.Object> val_58 = new System.Collections.Generic.List<System.Object>();
        val_58.Add(item:  40);
        val_58.Add(item:  45);
        val_58.Add(item:  50);
        .threshold = "60";
        .rewards = val_58;
        val_53.Add(item:  new GiftRewardTier(threshold:  "60", rewards:  val_58));
        System.Collections.Generic.List<System.Object> val_60 = new System.Collections.Generic.List<System.Object>();
        val_60.Add(item:  30);
        val_60.Add(item:  35);
        val_60.Add(item:  40);
        .threshold = "120";
        .rewards = val_60;
        val_53.Add(item:  new GiftRewardTier(threshold:  "120", rewards:  val_60));
        System.Collections.Generic.List<System.Object> val_62 = new System.Collections.Generic.List<System.Object>();
        val_62.Add(item:  20);
        val_62.Add(item:  25);
        val_62.Add(item:  30);
        .threshold = "350";
        .rewards = val_62;
        val_53.Add(item:  new GiftRewardTier(threshold:  "350", rewards:  val_62));
        System.Collections.Generic.List<System.Object> val_64 = new System.Collections.Generic.List<System.Object>();
        val_64.Add(item:  15);
        val_64.Add(item:  20);
        val_64.Add(item:  25);
        .threshold = "500";
        .rewards = val_64;
        val_53.Add(item:  new GiftRewardTier(threshold:  "500", rewards:  val_64));
        System.Collections.Generic.List<System.Object> val_66 = new System.Collections.Generic.List<System.Object>();
        val_66.Add(item:  10);
        val_66.Add(item:  15);
        val_66.Add(item:  20);
        .threshold = "1000";
        .rewards = val_66;
        val_53.Add(item:  new GiftRewardTier(threshold:  "1000", rewards:  val_66));
        GiftRewardData.DailyChallengeCoinRewardTiers = val_53;
        System.Collections.Generic.List<GiftRewardTypeChance> val_68 = new System.Collections.Generic.List<GiftRewardTypeChance>();
        .RewardType = 2.12199579096527E-312;
        val_68.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098009E-312;
        val_68.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098009E-312;
        val_68.Add(item:  new GiftRewardTypeChance());
        .RewardType = 5.3049894775614E-313;
        val_68.Add(item:  new GiftRewardTypeChance());
        GiftRewardData.DailyChallengeWeeklyRewardChances = val_68;
        System.Collections.Generic.List<GiftRewardTypeChance> val_73 = new System.Collections.Generic.List<GiftRewardTypeChance>();
        .RewardType = 2.12199579096527E-312;
        val_73.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098009E-312;
        val_73.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098009E-312;
        val_73.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579098009E-312;
        val_73.Add(item:  new GiftRewardTypeChance());
        .RewardType = 5.3049894775614E-313;
        val_73.Add(item:  new GiftRewardTypeChance());
        .RewardType = 3.18299368659613E-313;
        val_73.Add(item:  new GiftRewardTypeChance());
        .RewardType = 2.12199579097021E-312;
        val_73.Add(item:  new GiftRewardTypeChance());
        GiftRewardData.DailyChallengeMonthlyRewardChances = val_73;
        System.Collections.Generic.List<GiftRewardAmountChance> val_81 = new System.Collections.Generic.List<GiftRewardAmountChance>();
        .Amount = 1;
        .Chance = 60f;
        val_81.Add(item:  new GiftRewardAmountChance());
        .Amount = 2;
        .Chance = 40f;
        val_81.Add(item:  new GiftRewardAmountChance());
        GiftRewardData.DailyChallengeRewardFoodAmountChances = val_81;
    }

}
