using UnityEngine;
public class ZooTilePool
{
    // Fields
    public static System.Collections.Generic.List<ZooTile> LifetimeZooTiles;
    public static System.Collections.Generic.List<ZooTile> MonthlyZooTiles;
    
    // Methods
    public ZooTilePool()
    {
    
    }
    private static ZooTilePool()
    {
        System.Collections.Generic.List<ZooTile> val_1 = new System.Collections.Generic.List<ZooTile>();
        .name = "Sheep";
        .requiredStars = 1;
        .funFact = "A sheep\'s wool never stops growing.";
        val_1.Add(item:  new ZooTile());
        .name = "Sloth";
        .requiredStars = 5;
        .funFact = "Sloths can take a week to digest their food.";
        val_1.Add(item:  new ZooTile());
        .name = "Chinchilla";
        .requiredStars = 10;
        .funFact = "Chinchillas bathe in volcanic ash to keep their fur clean.";
        val_1.Add(item:  new ZooTile());
        .name = "Penguin";
        .requiredStars = 15;
        .funFact = "Penguins give their mates a rock or pebble as a gift.";
        val_1.Add(item:  new ZooTile());
        .name = "Wolf";
        .requiredStars = 25;
        .funFact = "Wolves live in packs of up to 20.";
        val_1.Add(item:  new ZooTile());
        .name = "Ostrich";
        .requiredStars = 50;
        .funFact = "Ostriches can run faster than most horses.";
        val_1.Add(item:  new ZooTile());
        .name = "Crocodile";
        .requiredStars = 75;
        .funFact = "Crocodiles do not have sweat glands and release heat through their mouths. They often sleep with their mouths open and may pant like a dog.";
        val_1.Add(item:  new ZooTile());
        .name = "Zebra";
        .requiredStars = 100;
        .funFact = "Every zebra has a unique pattern of black and white stripes.";
        val_1.Add(item:  new ZooTile());
        .name = "Kangaroo";
        .requiredStars = 125;
        .funFact = "Kangaroos cannot walk backwards.";
        val_1.Add(item:  new ZooTile());
        .name = "Gorilla";
        .requiredStars = 150;
        .funFact = "Gorillas have unique noseprints, much like human fingerprints, which can be used to identify individuals.";
        val_1.Add(item:  new ZooTile());
        .name = "Giraffe";
        .requiredStars = 175;
        .funFact = "Baby giraffes can stand up and even run within an hour of being born.";
        val_1.Add(item:  new ZooTile());
        .name = "Koala";
        .requiredStars = 200;
        .funFact = "Koalas can sleep up to 20 hours a day.";
        val_1.Add(item:  new ZooTile());
        .name = "Owl";
        .requiredStars = 250;
        .funFact = "Owls can rotate their necks 270 degrees.";
        val_1.Add(item:  new ZooTile());
        .name = "Hippo";
        .requiredStars = 300;
        .funFact = "Hippos can\'t swim.";
        val_1.Add(item:  new ZooTile());
        .name = "Tiger";
        .requiredStars = 350;
        .funFact = "The tiger is the biggest species of the cat family.";
        val_1.Add(item:  new ZooTile());
        .name = "Rhino";
        .requiredStars = 400;
        .funFact = "Rhino horns are made of keratin, the same substance that makes up human nails and hair.";
        val_1.Add(item:  new ZooTile());
        .name = "Elephant";
        .requiredStars = 450;
        .funFact = "Elephants can\'t jump.";
        val_1.Add(item:  new ZooTile());
        .name = "Lion";
        .requiredStars = 500;
        .funFact = "A lion’s roar can be heard from as far as 5 miles away.";
        val_1.Add(item:  new ZooTile());
        .name = "Skunk";
        .requiredStars = 600;
        .funFact = "The smell of a skunk can be detected by a human a mile away.";
        val_1.Add(item:  new ZooTile());
        .name = "Hummingbird";
        .requiredStars = 750;
        .funFact = "Hummingbirds beat their wings 60 to 80 times per second.";
        val_1.Add(item:  new ZooTile());
        .name = "Dolphin";
        .requiredStars = 1000;
        .funFact = "Dolphins have names for one other.";
        val_1.Add(item:  new ZooTile());
        .name = "Sea Otter";
        .requiredStars = 1500;
        .funFact = "Sea otters hold each other\'s paws when they sleep so they don\'t drift apart.";
        val_1.Add(item:  new ZooTile());
        .name = "Bear";
        .requiredStars = 2000;
        .funFact = "Bears can be found in almost all areas within the temperate zones of the earth.";
        val_1.Add(item:  new ZooTile());
        ZooTilePool.LifetimeZooTiles = val_1;
        System.Collections.Generic.List<ZooTile> val_25 = new System.Collections.Generic.List<ZooTile>();
        .name = "Monkey";
        .requiredStars = 100;
        .funFact = "Groups of monkeys are known as a ‘tribe’.";
        val_25.Add(item:  new ZooTile());
        .name = "Rabbit";
        .requiredStars = 100;
        .funFact = "Rabbits purr when they’re content.";
        val_25.Add(item:  new ZooTile());
        .name = "Ant";
        .requiredStars = 100;
        .funFact = "For every human in the world there are one million ants.";
        val_25.Add(item:  new ZooTile());
        .name = "Snake";
        .requiredStars = 100;
        .funFact = "Snakes can open their mouths up to 150 degrees.";
        val_25.Add(item:  new ZooTile());
        .name = "Beaver";
        .requiredStars = 100;
        .funFact = "The large front teeth of the beaver never stop growing.";
        val_25.Add(item:  new ZooTile());
        .name = "Snail";
        .requiredStars = 100;
        .funFact = "A snail can sleep for three years.";
        val_25.Add(item:  new ZooTile());
        .name = "Flamingo";
        .requiredStars = 100;
        .funFact = "A group of flamingos is called a \"flamboyance.\"";
        val_25.Add(item:  new ZooTile());
        .name = "Woodpecker";
        .requiredStars = 100;
        .funFact = "A woodpecker can peck 20 times per second.";
        val_25.Add(item:  new ZooTile());
        .name = "Horse";
        .requiredStars = 100;
        .funFact = "Horses were domesticated by humans more than 3000 years ago.";
        val_25.Add(item:  new ZooTile());
        .name = "Lizard";
        .requiredStars = 100;
        .funFact = "Lizards can detach their tails if caught by predators.";
        val_25.Add(item:  new ZooTile());
        .name = "Fox";
        .requiredStars = 100;
        .funFact = "Arctic Foxes don\'t shiver until -70° celsius.";
        val_25.Add(item:  new ZooTile());
        .name = "Moose";
        .requiredStars = 100;
        .funFact = "Moose lose their antlers once a year.";
        val_25.Add(item:  new ZooTile());
        .name = "Pig";
        .requiredStars = 100;
        .funFact = "Pigs don\'t sweat.";
        val_25.Add(item:  new ZooTile());
        .name = "Goat";
        .requiredStars = 100;
        .funFact = "Goats were the first animals domesticated by man in 10,000 B.C.";
        val_25.Add(item:  new ZooTile());
        .name = "Rooster";
        .requiredStars = 100;
        .funFact = "Roosters love to crow at any time of day, not just sunrise.";
        val_25.Add(item:  new ZooTile());
        .name = "Bat";
        .requiredStars = 100;
        .funFact = "Bats are the only mammals that can fly.";
        val_25.Add(item:  new ZooTile());
        .name = "Squirrel";
        .requiredStars = 100;
        .funFact = "Millions of trees grow every year thanks to squirrel\'s forgetting where they put their nuts.";
        val_25.Add(item:  new ZooTile());
        .name = "Rat";
        .requiredStars = 100;
        .funFact = "Rats can laugh.";
        val_25.Add(item:  new ZooTile());
        ZooTilePool.MonthlyZooTiles = val_25;
    }

}
