using UnityEngine;

namespace SnakesAndLaddersEvent
{
    public class Econ
    {
        // Fields
        public static int DefaultDiceRolls;
        public static int DiceRollLevelInterval;
        public static int StarterDicePackDurationInMinutes;
        public static System.Collections.Generic.List<GiftRewardAmountChance> DailyBonusDiceRollAmountChances;
        public static System.Collections.Generic.List<GiftRewardAmountChance> RewardSpaceCoinAmountChances;
        public static System.Collections.Generic.List<GiftRewardAmountChance> RewardSpaceDiceRollAmountChances;
        public static System.Collections.Generic.List<GiftRewardAmountChance> RewardSpaceGoldenCurrencyAmountChances;
        public static System.Collections.Generic.List<GiftRewardTypeChance> BoardSpaceRewardTypeChancesData;
        public static System.Collections.Generic.List<GiftRewardTypeChance> BoardSpaceRewardTypeChances;
        public static System.Collections.Generic.List<System.Collections.Generic.List<GiftRewardTypeChance>> BoardGiftRewardTypeChances;
        public static System.Collections.Generic.List<GiftRewardTier> BoardGiftCoinRewardTiers;
        public static System.Collections.Generic.List<GiftRewardAmountChance> BoardGiftRewardFoodAmountChances;
        public static System.Collections.Generic.List<GiftRewardAmountChance> BoardGiftRewardDiceRollAmountChances;
        public static System.Collections.Generic.List<SnakesAndLaddersEvent.BoardDefinition> BoardDefinitions;
        
        // Methods
        public Econ()
        {
        
        }
        private static Econ()
        {
            SnakesAndLaddersEvent.Econ.DefaultDiceRolls = 20;
            SnakesAndLaddersEvent.Econ.DiceRollLevelInterval = 3;
            SnakesAndLaddersEvent.Econ.StarterDicePackDurationInMinutes = 15;
            System.Collections.Generic.List<GiftRewardAmountChance> val_1 = new System.Collections.Generic.List<GiftRewardAmountChance>();
            val_1.Add(item:  new GiftRewardAmountChance(amount:  1, chance:  25f));
            val_1.Add(item:  new GiftRewardAmountChance(amount:  2, chance:  30f));
            val_1.Add(item:  new GiftRewardAmountChance(amount:  3, chance:  20f));
            val_1.Add(item:  new GiftRewardAmountChance(amount:  4, chance:  15f));
            val_1.Add(item:  new GiftRewardAmountChance(amount:  5, chance:  10f));
            SnakesAndLaddersEvent.Econ.DailyBonusDiceRollAmountChances = val_1;
            System.Collections.Generic.List<GiftRewardAmountChance> val_7 = new System.Collections.Generic.List<GiftRewardAmountChance>();
            val_7.Add(item:  new GiftRewardAmountChance(amount:  1, chance:  15f));
            val_7.Add(item:  new GiftRewardAmountChance(amount:  3, chance:  20f));
            val_7.Add(item:  new GiftRewardAmountChance(amount:  5, chance:  10f));
            SnakesAndLaddersEvent.Econ.RewardSpaceCoinAmountChances = val_7;
            System.Collections.Generic.List<GiftRewardAmountChance> val_11 = new System.Collections.Generic.List<GiftRewardAmountChance>();
            val_11.Add(item:  new GiftRewardAmountChance(amount:  1, chance:  10f));
            val_11.Add(item:  new GiftRewardAmountChance(amount:  2, chance:  5f));
            SnakesAndLaddersEvent.Econ.RewardSpaceDiceRollAmountChances = val_11;
            System.Collections.Generic.List<GiftRewardAmountChance> val_14 = new System.Collections.Generic.List<GiftRewardAmountChance>();
            val_14.Add(item:  new GiftRewardAmountChance(amount:  50, chance:  15f));
            val_14.Add(item:  new GiftRewardAmountChance(amount:  100, chance:  25f));
            SnakesAndLaddersEvent.Econ.RewardSpaceGoldenCurrencyAmountChances = val_14;
            System.Collections.Generic.List<GiftRewardTypeChance> val_17 = new System.Collections.Generic.List<GiftRewardTypeChance>();
            val_17.Add(item:  new GiftRewardTypeChance(rewardType:  0, chance:  45));
            val_17.Add(item:  new GiftRewardTypeChance(rewardType:  4, chance:  15));
            val_17.Add(item:  new GiftRewardTypeChance(rewardType:  5, chance:  40));
            SnakesAndLaddersEvent.Econ.BoardSpaceRewardTypeChancesData = val_17;
            SnakesAndLaddersEvent.Econ.BoardSpaceRewardTypeChances = new System.Collections.Generic.List<GiftRewardTypeChance>();
            System.Collections.Generic.List<System.Collections.Generic.List<GiftRewardTypeChance>> val_22 = new System.Collections.Generic.List<System.Collections.Generic.List<GiftRewardTypeChance>>();
            System.Collections.Generic.List<GiftRewardTypeChance> val_23 = new System.Collections.Generic.List<GiftRewardTypeChance>();
            val_23.Add(item:  new GiftRewardTypeChance(rewardType:  0, chance:  100));
            val_23.Add(item:  new GiftRewardTypeChance(rewardType:  4, chance:  100));
            val_23.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_22.Add(item:  val_23);
            System.Collections.Generic.List<GiftRewardTypeChance> val_27 = new System.Collections.Generic.List<GiftRewardTypeChance>();
            val_27.Add(item:  new GiftRewardTypeChance(rewardType:  0, chance:  100));
            val_27.Add(item:  new GiftRewardTypeChance(rewardType:  4, chance:  100));
            val_27.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_27.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_22.Add(item:  val_27);
            System.Collections.Generic.List<GiftRewardTypeChance> val_32 = new System.Collections.Generic.List<GiftRewardTypeChance>();
            val_32.Add(item:  new GiftRewardTypeChance(rewardType:  0, chance:  100));
            val_32.Add(item:  new GiftRewardTypeChance(rewardType:  4, chance:  100));
            val_32.Add(item:  new GiftRewardTypeChance(rewardType:  4, chance:  100));
            val_32.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_32.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_22.Add(item:  val_32);
            System.Collections.Generic.List<GiftRewardTypeChance> val_38 = new System.Collections.Generic.List<GiftRewardTypeChance>();
            val_38.Add(item:  new GiftRewardTypeChance(rewardType:  0, chance:  100));
            val_38.Add(item:  new GiftRewardTypeChance(rewardType:  4, chance:  100));
            val_38.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_38.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_38.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_22.Add(item:  val_38);
            System.Collections.Generic.List<GiftRewardTypeChance> val_44 = new System.Collections.Generic.List<GiftRewardTypeChance>();
            val_44.Add(item:  new GiftRewardTypeChance(rewardType:  0, chance:  100));
            val_44.Add(item:  new GiftRewardTypeChance(rewardType:  1, chance:  100));
            val_44.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_44.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_44.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            val_44.Add(item:  new GiftRewardTypeChance(rewardType:  3, chance:  100));
            System.Collections.Generic.List<GiftRewardTier> val_51 = val_22;
            val_22.Add(item:  val_44);
            SnakesAndLaddersEvent.Econ.BoardGiftRewardTypeChances = val_22;
            val_51 = new System.Collections.Generic.List<GiftRewardTier>();
            System.Collections.Generic.List<System.Object> val_52 = new System.Collections.Generic.List<System.Object>();
            val_52.Add(item:  100);
            val_52.Add(item:  110);
            val_52.Add(item:  120);
            val_22.Add(item:  new GiftRewardTier(threshold:  "0", rewards:  val_52));
            System.Collections.Generic.List<System.Object> val_54 = new System.Collections.Generic.List<System.Object>();
            val_54.Add(item:  70);
            val_54.Add(item:  80);
            val_54.Add(item:  90);
            val_22.Add(item:  new GiftRewardTier(threshold:  "30", rewards:  val_54));
            System.Collections.Generic.List<System.Object> val_56 = new System.Collections.Generic.List<System.Object>();
            val_56.Add(item:  40);
            val_56.Add(item:  45);
            val_56.Add(item:  50);
            val_22.Add(item:  new GiftRewardTier(threshold:  "60", rewards:  val_56));
            System.Collections.Generic.List<System.Object> val_58 = new System.Collections.Generic.List<System.Object>();
            val_58.Add(item:  30);
            val_58.Add(item:  35);
            val_58.Add(item:  40);
            val_22.Add(item:  new GiftRewardTier(threshold:  "120", rewards:  val_58));
            System.Collections.Generic.List<System.Object> val_60 = new System.Collections.Generic.List<System.Object>();
            val_60.Add(item:  20);
            val_60.Add(item:  25);
            val_60.Add(item:  30);
            val_22.Add(item:  new GiftRewardTier(threshold:  "350", rewards:  val_60));
            System.Collections.Generic.List<System.Object> val_62 = new System.Collections.Generic.List<System.Object>();
            val_62.Add(item:  15);
            val_62.Add(item:  20);
            val_62.Add(item:  25);
            val_22.Add(item:  new GiftRewardTier(threshold:  "500", rewards:  val_62));
            System.Collections.Generic.List<System.Object> val_64 = new System.Collections.Generic.List<System.Object>();
            val_64.Add(item:  10);
            val_64.Add(item:  15);
            val_64.Add(item:  10);
            val_22.Add(item:  new GiftRewardTier(threshold:  "1000", rewards:  val_64));
            SnakesAndLaddersEvent.Econ.BoardGiftCoinRewardTiers = val_51;
            System.Collections.Generic.List<GiftRewardAmountChance> val_66 = new System.Collections.Generic.List<GiftRewardAmountChance>();
            val_66.Add(item:  new GiftRewardAmountChance(amount:  1, chance:  60f));
            val_66.Add(item:  new GiftRewardAmountChance(amount:  2, chance:  40f));
            SnakesAndLaddersEvent.Econ.BoardGiftRewardFoodAmountChances = val_66;
            System.Collections.Generic.List<GiftRewardAmountChance> val_69 = new System.Collections.Generic.List<GiftRewardAmountChance>();
            val_69.Add(item:  new GiftRewardAmountChance(amount:  1, chance:  5f));
            val_69.Add(item:  new GiftRewardAmountChance(amount:  2, chance:  12.5f));
            val_69.Add(item:  new GiftRewardAmountChance(amount:  3, chance:  20f));
            val_69.Add(item:  new GiftRewardAmountChance(amount:  4, chance:  25f));
            val_69.Add(item:  new GiftRewardAmountChance(amount:  5, chance:  20f));
            val_69.Add(item:  new GiftRewardAmountChance(amount:  6, chance:  12.5f));
            val_69.Add(item:  new GiftRewardAmountChance(amount:  7, chance:  5f));
            SnakesAndLaddersEvent.Econ.BoardGiftRewardDiceRollAmountChances = val_69;
            System.Collections.Generic.List<SnakesAndLaddersEvent.BoardDefinition> val_77 = new System.Collections.Generic.List<SnakesAndLaddersEvent.BoardDefinition>();
            System.Collections.Generic.List<System.Int32> val_78 = new System.Collections.Generic.List<System.Int32>();
            val_78.Add(item:  3);
            val_78.Add(item:  8);
            val_78.Add(item:  16);
            val_78.Add(item:  23);
            val_78.Add(item:  25);
            val_78.Add(item:  31);
            val_78.Add(item:  40);
            val_78.Add(item:  46);
            val_78.Add(item:  49);
            val_78.Add(item:  56);
            val_78.Add(item:  62);
            val_78.Add(item:  69);
            val_78.Add(item:  78);
            val_78.Add(item:  81);
            val_78.Add(item:  84);
            val_78.Add(item:  87);
            val_78.Add(item:  92);
            System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition> val_79 = new System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition>();
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  1, numberConnected:  26));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  9, numberConnected:  17));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  10, numberConnected:  4));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  20, numberConnected:  30));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  28, numberConnected:  14));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  38, numberConnected:  59));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  39, numberConnected:  33));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  41, numberConnected:  48));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  50, numberConnected:  45));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  52, numberConnected:  68));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  66, numberConnected:  57));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  72, numberConnected:  82));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  77, numberConnected:  88));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  79, numberConnected:  76));
            val_79.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  86, numberConnected:  63));
            val_77.Add(item:  new SnakesAndLaddersEvent.BoardDefinition(maxBoardSpaces:  96, rewardSpaceIndices:  val_78, numberSpaceConnections:  val_79));
            System.Collections.Generic.List<System.Int32> val_96 = new System.Collections.Generic.List<System.Int32>();
            val_96.Add(item:  3);
            val_96.Add(item:  11);
            val_96.Add(item:  16);
            val_96.Add(item:  21);
            val_96.Add(item:  24);
            val_96.Add(item:  26);
            val_96.Add(item:  34);
            val_96.Add(item:  36);
            val_96.Add(item:  42);
            val_96.Add(item:  48);
            val_96.Add(item:  51);
            val_96.Add(item:  58);
            val_96.Add(item:  62);
            val_96.Add(item:  70);
            val_96.Add(item:  76);
            val_96.Add(item:  77);
            val_96.Add(item:  83);
            val_96.Add(item:  87);
            val_96.Add(item:  90);
            val_96.Add(item:  91);
            val_96.Add(item:  98);
            val_96.Add(item:  100);
            val_96.Add(item:  106);
            System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition> val_97 = new System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition>();
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  2, numberConnected:  36));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  7, numberConnected:  18));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  15, numberConnected:  29));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  17, numberConnected:  9));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  27, numberConnected:  14));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  33, numberConnected:  20));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  40, numberConnected:  48));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  50, numberConnected:  58));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  52, numberConnected:  38));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  57, numberConnected:  75));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  61, numberConnected:  71));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  65, numberConnected:  88));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  66, numberConnected:  41));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  73, numberConnected:  62));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  86, numberConnected:  96));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  94, numberConnected:  104));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  103, numberConnected:  92));
            val_97.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  107, numberConnected:  98));
            val_77.Add(item:  new SnakesAndLaddersEvent.BoardDefinition(maxBoardSpaces:  108, rewardSpaceIndices:  val_96, numberSpaceConnections:  val_97));
            System.Collections.Generic.List<System.Int32> val_117 = new System.Collections.Generic.List<System.Int32>();
            val_117.Add(item:  4);
            val_117.Add(item:  7);
            val_117.Add(item:  11);
            val_117.Add(item:  15);
            val_117.Add(item:  22);
            val_117.Add(item:  30);
            val_117.Add(item:  33);
            val_117.Add(item:  36);
            val_117.Add(item:  39);
            val_117.Add(item:  44);
            val_117.Add(item:  45);
            val_117.Add(item:  47);
            val_117.Add(item:  51);
            val_117.Add(item:  59);
            val_117.Add(item:  60);
            val_117.Add(item:  63);
            val_117.Add(item:  67);
            val_117.Add(item:  69);
            val_117.Add(item:  75);
            val_117.Add(item:  81);
            val_117.Add(item:  87);
            val_117.Add(item:  91);
            val_117.Add(item:  95);
            val_117.Add(item:  97);
            val_117.Add(item:  100);
            val_117.Add(item:  106);
            val_117.Add(item:  113);
            val_117.Add(item:  119);
            System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition> val_118 = new System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition>();
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  3, numberConnected:  49));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  9, numberConnected:  22));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  12, numberConnected:  2));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  20, numberConnected:  42));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  24, numberConnected:  45));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  28, numberConnected:  18));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  40, numberConnected:  59));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  41, numberConnected:  33));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  52, numberConnected:  47));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  64, numberConnected:  58));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  65, numberConnected:  107));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  71, numberConnected:  80));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  77, numberConnected:  69));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  79, numberConnected:  67));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  84, numberConnected:  96));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  86, numberConnected:  73));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  93, numberConnected:  104));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  102, numberConnected:  72));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  103, numberConnected:  114));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  108, numberConnected:  118));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  111, numberConnected:  95));
            val_118.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  117, numberConnected:  105));
            val_77.Add(item:  new SnakesAndLaddersEvent.BoardDefinition(maxBoardSpaces:  120, rewardSpaceIndices:  val_117, numberSpaceConnections:  val_118));
            System.Collections.Generic.List<System.Int32> val_142 = new System.Collections.Generic.List<System.Int32>();
            val_142.Add(item:  4);
            val_142.Add(item:  12);
            val_142.Add(item:  17);
            val_142.Add(item:  19);
            val_142.Add(item:  21);
            val_142.Add(item:  23);
            val_142.Add(item:  27);
            val_142.Add(item:  33);
            val_142.Add(item:  35);
            val_142.Add(item:  37);
            val_142.Add(item:  44);
            val_142.Add(item:  45);
            val_142.Add(item:  49);
            val_142.Add(item:  51);
            val_142.Add(item:  54);
            val_142.Add(item:  56);
            val_142.Add(item:  62);
            val_142.Add(item:  63);
            val_142.Add(item:  65);
            val_142.Add(item:  72);
            val_142.Add(item:  75);
            val_142.Add(item:  81);
            val_142.Add(item:  93);
            val_142.Add(item:  94);
            val_142.Add(item:  95);
            val_142.Add(item:  104);
            val_142.Add(item:  105);
            val_142.Add(item:  110);
            val_142.Add(item:  118);
            val_142.Add(item:  120);
            val_142.Add(item:  123);
            val_142.Add(item:  125);
            val_142.Add(item:  130);
            System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition> val_143 = new System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition>();
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  2, numberConnected:  66));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  8, numberConnected:  27));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  9, numberConnected:  5));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  13, numberConnected:  34));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  14, numberConnected:  12));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  29, numberConnected:  75));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  30, numberConnected:  20));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  39, numberConnected:  25));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  42, numberConnected:  54));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  47, numberConnected:  60));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  58, numberConnected:  73));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  59, numberConnected:  37));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  68, numberConnected:  51));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  77, numberConnected:  89));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  79, numberConnected:  67));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  83, numberConnected:  96));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  87, numberConnected:  108));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  88, numberConnected:  62));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  99, numberConnected:  131));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  100, numberConnected:  92));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  114, numberConnected:  104));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  117, numberConnected:  128));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  121, numberConnected:  105));
            val_143.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  129, numberConnected:  109));
            val_77.Add(item:  new SnakesAndLaddersEvent.BoardDefinition(maxBoardSpaces:  132, rewardSpaceIndices:  val_142, numberSpaceConnections:  val_143));
            System.Collections.Generic.List<System.Int32> val_169 = new System.Collections.Generic.List<System.Int32>();
            val_169.Add(item:  2);
            val_169.Add(item:  10);
            val_169.Add(item:  12);
            val_169.Add(item:  16);
            val_169.Add(item:  17);
            val_169.Add(item:  24);
            val_169.Add(item:  30);
            val_169.Add(item:  33);
            val_169.Add(item:  35);
            val_169.Add(item:  38);
            val_169.Add(item:  48);
            val_169.Add(item:  53);
            val_169.Add(item:  59);
            val_169.Add(item:  65);
            val_169.Add(item:  68);
            val_169.Add(item:  70);
            val_169.Add(item:  72);
            val_169.Add(item:  74);
            val_169.Add(item:  76);
            val_169.Add(item:  81);
            val_169.Add(item:  82);
            val_169.Add(item:  89);
            val_169.Add(item:  91);
            val_169.Add(item:  94);
            val_169.Add(item:  96);
            val_169.Add(item:  107);
            val_169.Add(item:  110);
            val_169.Add(item:  112);
            val_169.Add(item:  115);
            val_169.Add(item:  119);
            val_169.Add(item:  128);
            val_169.Add(item:  132);
            val_169.Add(item:  134);
            val_169.Add(item:  135);
            val_169.Add(item:  140);
            System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition> val_170 = new System.Collections.Generic.List<SnakesAndLaddersEvent.NumberSpaceConnectionDefinition>();
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  3, numberConnected:  59));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  5, numberConnected:  18));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  14, numberConnected:  1));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  20, numberConnected:  16));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  26, numberConnected:  44));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  39, numberConnected:  19));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  42, numberConnected:  80));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  46, numberConnected:  32));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  51, numberConnected:  64));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  60, numberConnected:  25));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  62, numberConnected:  102));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  63, numberConnected:  52));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  84, numberConnected:  69));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  86, numberConnected:  109));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  87, numberConnected:  61));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  99, numberConnected:  96));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  100, numberConnected:  104));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  106, numberConnected:  115));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  114, numberConnected:  103));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  118, numberConnected:  144));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  124, numberConnected:  137));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  138, numberConnected:  177));
            val_170.Add(item:  new SnakesAndLaddersEvent.NumberSpaceConnectionDefinition(number:  142, numberConnected:  119));
            val_77.Add(item:  new SnakesAndLaddersEvent.BoardDefinition(maxBoardSpaces:  144, rewardSpaceIndices:  val_169, numberSpaceConnections:  val_170));
            SnakesAndLaddersEvent.Econ.BoardDefinitions = val_77;
        }
    
    }

}
